import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        surface: "#fef7ff",
        "surface-dim": "#ded7e4",
        "surface-bright": "#fef7ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f8f1fe",
        "surface-container": "#f3ebf8",
        "surface-container-high": "#ede5f3",
        "surface-container-highest": "#e7e0ed",
        "on-surface": "#1d1a23",
        "on-surface-variant": "#494454",
        "inverse-surface": "#322f39",
        "inverse-on-surface": "#f5eefb",
        outline: "#7b7486",
        "outline-variant": "#cbc3d7",
        "surface-tint": "#6d3bd7",
        primary: "#6b38d4",
        "on-primary": "#ffffff",
        "primary-container": "#8455ef",
        "on-primary-container": "#fffbff",
        "inverse-primary": "#d0bcff",
        secondary: "#7a580f",
        "on-secondary": "#ffffff",
        "secondary-container": "#ffd07d",
        "on-secondary-container": "#79570e",
        tertiary: "#b10e6b",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#d23284",
        "on-tertiary-container": "#fffbff",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#e9ddff",
        "primary-fixed-dim": "#d0bcff",
        "on-primary-fixed": "#23005c",
        "on-background": "#1d1a23",
        "surface-variant": "#e7e0ed",
      },
      fontFamily: {
        display: ["var(--font-playfair)", "serif"],
        body: ["var(--font-inter)", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["80px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-md": ["56px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg": ["40px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-lg-mobile": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-xl": ["20px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "600" }],
      },
      maxWidth: {
        "container-max": "1280px",
      },
      spacing: {
        gutter: "32px",
        unit: "8px",
        "stack-lg": "80px",
        "stack-md": "48px",
        "stack-sm": "24px",
        "margin-desktop": "64px",
        "margin-mobile": "24px",
      },
    },
  },
  plugins: [],
};
export default config;
